import image1 from '../Pictures/Food2.jpg'
import image2 from '../Pictures/Food1.jpg'
import image3 from '../Pictures/Food3.jpg'

export const foodsOfTwelve = [
  {
    id: 1,
    name: 'Stir fry Pasta',
    img: image1,
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem assumenda inventore sunt et debitis? Vero dicta sapiente neque voluptatum impedit quos ipsum, vitae quisquam voluptatem officiis nesciunt aliquam iste blanditiis ut laboriosam, vel odio? Voluptas.',
    price: 10,
    time: '10-30mins',
    avai: '10 Pcs Avail',
  },
  {
    id: 2,
    name: 'Meat Balls',
    img: image2,
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem assumenda inventore sunt et debitis? Vero dicta sapiente neque voluptatum impedit quos ipsum, vitae quisquam voluptatem officiis nesciunt aliquam iste blanditiis ut laboriosam, vel odio? Voluptas.',
    price: 9,
    time: '10-30mins',
    avai: '16 Pcs Avail',
  },
  {
    id: 3,
    name: 'Burger Meat',
    img: image3,
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem assumenda inventore sunt et debitis? Vero dicta sapiente neque voluptatum impedit quos ipsum, vitae quisquam voluptatem officiis nesciunt aliquam iste blanditiis ut laboriosam, vel odio? Voluptas.',
    price: 10,
    time: '10-30mins',
    avai: '11 Pcs Avail',
  },
  {
    id: 4,
    name: 'Stir fry Pasta',
    img: image1,
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem assumenda inventore sunt et debitis? Vero dicta sapiente neque voluptatum impedit quos ipsum, vitae quisquam voluptatem officiis nesciunt aliquam iste blanditiis ut laboriosam, vel odio? Voluptas.',
    price: 8,
    time: '10-30mins',
    avai: '16 Pcs Avail',
  },
  {
    id: 5,
    name: 'Meat Balls',
    img: image2,
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem assumenda inventore sunt et debitis? Vero dicta sapiente neque voluptatum impedit quos ipsum, vitae quisquam voluptatem officiis nesciunt aliquam iste blanditiis ut laboriosam, vel odio? Voluptas.',
    price: 12,
    time: '10-30mins',
    avai: '19 Pcs Avail',
  },
  {
    id: 6,
    name: 'Burger Meat',
    img: image3,
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem assumenda inventore sunt et debitis? Vero dicta sapiente neque voluptatum impedit quos ipsum, vitae quisquam voluptatem officiis nesciunt aliquam iste blanditiis ut laboriosam, vel odio? Voluptas.',
    price: 9,
    time: '10-30mins',
    avai: '14 Pcs Avail',
  },
  {
    id: 7,
    name: 'Stir fry Pasta',
    img: image1,
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem assumenda inventore sunt et debitis? Vero dicta sapiente neque voluptatum impedit quos ipsum, vitae quisquam voluptatem officiis nesciunt aliquam iste blanditiis ut laboriosam, vel odio? Voluptas.',
    price: 8,
    time: '10-30mins',
    avai: '11 Pcs Avail',
  },
  {
    id: 8,
    name: 'Meat Balls',
    img: image2,
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem assumenda inventore sunt et debitis? Vero dicta sapiente neque voluptatum impedit quos ipsum, vitae quisquam voluptatem officiis nesciunt aliquam iste blanditiis ut laboriosam, vel odio? Voluptas.',
    price: 11,
    time: '10-30mins',
    avai: '10 Pcs Avail',
  },
  {
    id: 9,
    name: 'Burger Meat',
    img: image3,
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem assumenda inventore sunt et debitis? Vero dicta sapiente neque voluptatum impedit quos ipsum, vitae quisquam voluptatem officiis nesciunt aliquam iste blanditiis ut laboriosam, vel odio? Voluptas.',
    price: 9,
    time: '10-30mins',
    avai: '13 Pcs Avail',
  },
  {
    id: 10,
    name: 'Stir fry Pasta',
    img: image1,
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem assumenda inventore sunt et debitis? Vero dicta sapiente neque voluptatum impedit quos ipsum, vitae quisquam voluptatem officiis nesciunt aliquam iste blanditiis ut laboriosam, vel odio? Voluptas.',
    price: 10,
    time: '10-30mins',
    avai: '18 Pcs Avail',
  },
  {
    id: 11,
    name: 'Meat Balls',
    img: image2,
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem assumenda inventore sunt et debitis? Vero dicta sapiente neque voluptatum impedit quos ipsum, vitae quisquam voluptatem officiis nesciunt aliquam iste blanditiis ut laboriosam, vel odio? Voluptas.',
    price: 9,
    time: '10-30mins',
    avai: '16 Pcs Avail',
  },
  {
    id: 12,
    name: 'Burger Meat',
    img: image3,
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem assumenda inventore sunt et debitis? Vero dicta sapiente neque voluptatum impedit quos ipsum, vitae quisquam voluptatem officiis nesciunt aliquam iste blanditiis ut laboriosam, vel odio? Voluptas.',
    price: 12,
    time: '10-30mins',
    avai: '13 Pcs Avail',
  },
]
